import type { Metadata } from "next";
// import open sans font
import { Open_Sans } from "next/font/google";
import "./globals.css";

//configure our font object
const openSans = Open_Sans({
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "My profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //attach font to global jsx node
    <html lang="en">
      <body className={openSans.className} >{children}</body>
    </html>
  );
}
